---
# tasks file for hswong3i.fisheye

- name: stop service if upgrade
  service: name=fisheye state=stopped
  when: fisheye_upgrade == true
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: remove legacy binary if upgrade
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ fisheye_catalina }}", owner: "{{ fisheye_user }}", group: "{{ fisheye_user }}", mode: '0755', state: 'absent' }
  when: fisheye_upgrade == true
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - ufw
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: create user
  user:
    name={{ fisheye_user }}
    password={{ fisheye_pass }}
    home={{ fisheye_home }}
    shell=/bin/bash
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ fisheye_catalina }}", owner: "{{ fisheye_user }}", group: "{{ fisheye_user }}", mode: '0755', state: 'directory' }
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: download package
  get_url:
    url={{ fisheye_url }}
    dest={{ fisheye_archive }}
    sha256sum={{ fisheye_sha256 }}
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: unarchive package
  shell: TMP_DIR=`mktemp -d`; unzip {{ fisheye_archive }} -x -d $TMP_DIR; rsync -av $TMP_DIR/*/ {{ fisheye_catalina }}; chown -Rf {{ fisheye_user }}:{{ fisheye_user }} {{ fisheye_catalina }}
  args:
    creates: "{{ fisheye_catalina }}/bin/start.sh"
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/init.d/fisheye.j2', dest: '/etc/init.d/fisheye', owner: 'root', group: 'root', mode: '0755' }
    - { src: 'usr/share/fisheye/bin/fisheyectl.sh.j2', dest: "{{ fisheye_catalina }}/bin/fisheyectl.sh", owner: "{{ fisheye_user }}", group: "{{ fisheye_user }}", mode: '0755' }
    - { src: 'usr/share/fisheye/config.xml.j2', dest: "{{ fisheye_catalina }}/config.xml", owner: "{{ fisheye_user }}", group: "{{ fisheye_user }}", mode: '0644' }
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: enable service
  service: name=fisheye enabled=yes
  notify: restart fisheye
  tags: hswong3i.fisheye

- name: enable incomming connection
  ufw:
    to_port={{ item }}
    proto=tcp
    rule=allow
  with_items:
    - "{{ fisheye_connector_port }}"
    - "{{ fisheye_server_port }}"
  notify: restart fisheye
  tags: hswong3i.fisheye
